name: release

on:
  push:
    tags:
    - '*'

# Taken mainly from https://franzramadhan.com/posts/8-how-to-publish-go-binary-to-homebrew/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install specific version of go
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      # Run goreleaser with command line flag
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: -f .goreleaser.yaml release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 